### ISSUE TITLE
glob resolution does not work (?)

### ISSUE THREAD

**Issue by patmuk** [Kaivosukeltaja/files-exist#2]
this is not working:
` 
it('should resolve glob requests', function() {
    var fileArray = ['lib/*.js'],
    options = { checkGlobs: true };
    var results = filesExist(fileArray, options);
console.log('results are: '+results);
    chai.expect('lib/files-exist.js' in results).to.not.equal(false);
  });
`
(you can add this to test/tests.js)
results are: lib/*.js
`    1) should resolve glob requests

  11 passing (27ms)
  1 failing

  1) filesExist should resolve glob requests:

      AssertionError: expected false to not equal false
      + expected - actual`

Or am I using it wrong?

**Comment by Kaivosukeltaja** [comment]
Hi! The module returns the items in the array **unchanged** if they match any existing files. If you check against `lib/*.js` the array will contain `lib/*.js` if there are any JS files inside lib. It will not expand the globs to actual matching files so `lib/files-exist.js` will not be there.

This functionality is by design to make comparing the results easier (you can just compare the size of the arrays). Do you have a use case for expanding globs to actual file names? I don't see any reason why it couldn't be added as a new feature behind a new option flag.

**Comment by patmuk** [comment]
Hi,

no, I was using it wrong :) All fine, did not realised this behaviour. It fits my use case.
Thanks for the good explanation!
